{% set version = "0.7.3" %}

package:
  name: ergocub-software-split
  version: {{ version }}

source:
  - url: https://github.com/icub-tech-iit/ergocub-software/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 346d3301da028dfe9e9d31bda259b39c8f6189a69d8bc713389ff0a0e42c02bb

build:
  number: 0

outputs:
  - name: libergocub-software
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("libergocub-software", max_pin='x.x.x') }}
      ignore_run_exports_from:
      # idyntree is just used for tests
        - idyntree
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
        - multisheller
      host:
        - ycm-cmake-modules
        - libyarp
        - libopencv
        - idyntree

    test:
      commands:
        - test -f ${PREFIX}/lib/yarp/yarp_couplingXCubHandMk5.so  # [unix]
        - if not exist %LIBRARY_LIB%\\yarp\\yarp_couplingXCubHandMk5.dll exit 1  # [win]

  - name: ergocub-software
    requirements:
      run:
        - {{ pin_subpackage("libergocub-software", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/lib/yarp/yarp_couplingXCubHandMk5.so  # [unix]
        - if not exist %LIBRARY_LIB%\\yarp\\yarp_couplingXCubHandMk5.dll exit 1  # [win]


about:
  home: https://github.com/icub-tech-iit/ergocub-software
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Software required to simulate and run the ergoCub humanoid robot.'

extra:
  feedstock-name: ergocub-software
  recipe-maintainers:
    - traversaro
